### ISSUE TITLE
是否可以弄一个播放历史记录。

### ISSUE THREAD

**Issue by Shaun-Shaw** [FaiChou/Aliplayer_About#2]
如题，另外开始播放时，如果左滑调播放列表容易误触成快退。播放过程中进度条发现有一定的概率消失。

**Comment by FaiChou** [comment]
播放器体验有待优化, 播放历史记录功能正在考虑.

**Comment by FaiChou** [comment]
@Shaun-Shaw  已经优化了, 可以更新试试
