### ISSUE TITLE
快进操作不是太方便

### ISSUE THREAD

**Issue by adamhuang666** [FaiChou/Aliplayer_About#3]
目前的快进：正常播放情况下，暂停/触摸板快进操作，播放进度条是红色情况下，可以快进一下，但是当进度条变成白色，则不可以进行快进

第一次操作这个，我以为是不支持或者不兼容导致，后来才发现操作方法和规律，但是这个就不是太方便操作，以为可能需要多次按快进健进行快进，但是目前是不支持的

期望可以支持改善目前的这个快进的操作方式，谢谢

**Comment by Shaun-Shaw** [comment]
感觉快进操作快了，容易卡死，进度条有时候白色，有时候蓝色，感觉逻辑有点奇怪。回退非常容易退到0，进度条运行是比较大的影响体验问题，其他的都挺好的。我的遥控器是最新款带实体按键的，不知道触摸的，会不会好点。
