### ISSUE TITLE
无法播放视频，播放按钮消失了

### ISSUE THREAD

**Issue by Hoshino324** [FaiChou/Aliplayer_About#5]
似乎是昨天阿里进行了什么操作，现在所有相关的东西都需要更新api？请问作者什么时候有空更新一下吧orz，apple tv买了pro的

**Comment by FaiChou** [comment]
关注 tg 频道, 发新的 tf 会通知的. https://t.me/alplayer_channel

**Comment by FaiChou** [comment]
https://testflight.apple.com/join/6R6lYvBn


更新了 TF 1.3 build 49 暂时修复了无法加载视频播放问题.

@Hoshino324
